/** Standard chart of accounts for a small Japanese corporation */
export const seedAccounts = [
  // === 資産 (Assets) ===
  { code: "1100", name: "現金", category: "asset" as const },
  { code: "1110", name: "小口現金", category: "asset" as const },
  { code: "1120", name: "普通預金", category: "asset" as const },
  { code: "1130", name: "当座預金", category: "asset" as const },
  { code: "1140", name: "定期預金", category: "asset" as const },
  { code: "1200", name: "売掛金", category: "asset" as const },
  { code: "1210", name: "受取手形", category: "asset" as const },
  { code: "1300", name: "棚卸資産", category: "asset" as const },
  { code: "1310", name: "商品", category: "asset" as const },
  { code: "1400", name: "前払金", category: "asset" as const },
  { code: "1410", name: "前払費用", category: "asset" as const },
  { code: "1420", name: "立替金", category: "asset" as const },
  { code: "1430", name: "仮払金", category: "asset" as const },
  { code: "1440", name: "仮払消費税", category: "asset" as const },
  { code: "1500", name: "未収入金", category: "asset" as const },
  { code: "1600", name: "貸付金", category: "asset" as const },
  { code: "1700", name: "建物", category: "asset" as const },
  { code: "1710", name: "建物附属設備", category: "asset" as const },
  { code: "1720", name: "車両運搬具", category: "asset" as const },
  { code: "1730", name: "工具器具備品", category: "asset" as const },
  { code: "1740", name: "土地", category: "asset" as const },
  { code: "1750", name: "ソフトウェア", category: "asset" as const },
  { code: "1800", name: "敷金・保証金", category: "asset" as const },
  { code: "1900", name: "減価償却累計額", category: "asset" as const },

  // === 負債 (Liabilities) ===
  { code: "2100", name: "買掛金", category: "liability" as const },
  { code: "2110", name: "支払手形", category: "liability" as const },
  { code: "2200", name: "短期借入金", category: "liability" as const },
  { code: "2300", name: "未払金", category: "liability" as const },
  { code: "2310", name: "未払費用", category: "liability" as const },
  { code: "2320", name: "未払法人税等", category: "liability" as const },
  { code: "2330", name: "未払消費税等", category: "liability" as const },
  { code: "2340", name: "預り金", category: "liability" as const },
  { code: "2350", name: "仮受金", category: "liability" as const },
  { code: "2360", name: "仮受消費税", category: "liability" as const },
  { code: "2400", name: "前受金", category: "liability" as const },
  { code: "2410", name: "前受収益", category: "liability" as const },
  { code: "2500", name: "長期借入金", category: "liability" as const },

  // === 純資産 (Equity) ===
  { code: "3100", name: "資本金", category: "equity" as const },
  { code: "3200", name: "資本剰余金", category: "equity" as const },
  { code: "3300", name: "利益剰余金", category: "equity" as const },
  { code: "3310", name: "繰越利益剰余金", category: "equity" as const },

  // === 収益 (Revenue) ===
  { code: "4100", name: "売上高", category: "revenue" as const },
  { code: "4200", name: "受取利息", category: "revenue" as const },
  { code: "4300", name: "受取配当金", category: "revenue" as const },
  { code: "4400", name: "雑収入", category: "revenue" as const },
  { code: "4500", name: "固定資産売却益", category: "revenue" as const },

  // === 費用 (Expenses) ===
  { code: "5100", name: "売上原価", category: "expense" as const },
  { code: "5110", name: "仕入高", category: "expense" as const },
  { code: "5200", name: "役員報酬", category: "expense" as const },
  { code: "5210", name: "給料賃金", category: "expense" as const },
  { code: "5220", name: "賞与", category: "expense" as const },
  { code: "5230", name: "法定福利費", category: "expense" as const },
  { code: "5240", name: "福利厚生費", category: "expense" as const },
  { code: "5300", name: "旅費交通費", category: "expense" as const },
  { code: "5310", name: "通信費", category: "expense" as const },
  { code: "5320", name: "消耗品費", category: "expense" as const },
  { code: "5330", name: "事務用品費", category: "expense" as const },
  { code: "5340", name: "地代家賃", category: "expense" as const },
  { code: "5350", name: "水道光熱費", category: "expense" as const },
  { code: "5360", name: "保険料", category: "expense" as const },
  { code: "5370", name: "修繕費", category: "expense" as const },
  { code: "5380", name: "広告宣伝費", category: "expense" as const },
  { code: "5390", name: "交際費", category: "expense" as const },
  { code: "5400", name: "会議費", category: "expense" as const },
  { code: "5410", name: "諸会費", category: "expense" as const },
  { code: "5420", name: "支払手数料", category: "expense" as const },
  { code: "5430", name: "外注費", category: "expense" as const },
  { code: "5440", name: "租税公課", category: "expense" as const },
  { code: "5450", name: "減価償却費", category: "expense" as const },
  { code: "5460", name: "リース料", category: "expense" as const },
  { code: "5470", name: "新聞図書費", category: "expense" as const },
  { code: "5480", name: "研修費", category: "expense" as const },
  { code: "5490", name: "雑費", category: "expense" as const },
  { code: "5500", name: "支払利息", category: "expense" as const },
  { code: "5600", name: "固定資産売却損", category: "expense" as const },
  { code: "5700", name: "法人税等", category: "expense" as const },
];
